=== FaKod/JPA-for-Scala/src/main/resources/META-INF/JPAExtension.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="snippet">
	    <xs:complexType>
	    	<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="jpql" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="jpqlsnippets">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="snippet" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="filter">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jpaextension">
		<xs:complexType>
			<xs:all>
				<xs:element ref="jpqlsnippets" minOccurs="0"/>
				<xs:element ref="filter" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="value"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="value">
		<xs:complexType mixed="true"/>
	</xs:element>
	<xs:element name="query">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="filterClass" minOccurs="0"/>
				<xs:element ref="fetch" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="jpql" type="xs:string" use="optional"/>
			<xs:attribute name="alias" type="xs:string" use="optional"/>
			<xs:attribute name="ext" type="xs:string" use="optional"/>
			<xs:attribute name="orderby" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="annotation" type="xs:string" use="optional"/>
			<!-- the jpql statement (where clause)-->
			<!-- settable alias for type of resultset-->
			<!-- extension for part after "from" -->
			<!-- for order by statement -->
			<!-- filter id -->
		</xs:complexType>
	</xs:element>
	<xs:element name="fetch">
		<xs:complexType>
			<xs:attribute name="property" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="joinType" use="optional" default="inner">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="inner"/>
						<xs:enumeration value="left"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="filterClass">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="binding" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="static" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="binding">
		<xs:complexType>
			<xs:attribute name="var" type="xs:NMTOKEN" use="required"/>
			<xs:attribute name="attribute" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="static">
		<xs:complexType>
			<xs:attribute name="statementAttribute" type="xs:NMTOKEN" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FaKod/JPA-for-Scala/src/test/resources/META-INF/JPAExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<jpaextension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JPAExtension.xsd">

    <jpqlsnippets>
        <snippet id="MY_LIKE_SNIPPET" jpql="like"/>
        <snippet id="nnaammee2" jpql="NAME=:NAME"/>
        <snippet id="nnaammee3" jpql="NAME=:UNIT"/>
    </jpqlsnippets>


    <!-- Definition of available Query Objects-->
    <filter>
        <!--special filter "name" for cluster CAuto is available-->
        <!--select: ...where NAME=test.testfilter.NameFilter.getName()-->
        <query id="query1" jpql="|nnaammee|" annotation="anno1 anno2 anno3 anno4 anno5">
            <filterClass class="org.jpaextension.test.data.Filter1">
                <binding var="UNITNAME" attribute="name"/>
            </filterClass>
        </query>
        <!--select for coordinates-->
        <query id="query2" alias="car" jpql="LATITUDE=:LAT and LONGITUDE=:LONG" annotation="anno6 anno7">
            <filterClass class="org.jpaextension.test.data.Filter2">
                <binding var="LONG" attribute="longitude"/>
                <binding var="LAT" attribute="latitude"/>
            </filterClass>
        </query>
        <!--select only for LATITUDE-->
        <query id="query3" jpql="LATITUDE=:LATONLY">
            <filterClass class="org.jpaextension.test.data.Filter3">
                <binding var="LATONLY" attribute="latitude"/>
            </filterClass>
        </query>
        <query id="query4">
            <filterClass class="org.jpaextension.test.data.Filter1"/>
        </query>
        <query id="query5" alias="c">
            <filterClass class="org.jpaextension.test.data.Filter2"/>
            <fetch property="besitzer"/>
            <fetch property="sparePart" joinType="left"/>
        </query>
        <query id="MyOIQuery" alias="oi" jpql="oi.creatorId=:CID and oi.nameTxt=:NT" annotation="anno6 anno7">
            <filterClass class="org.jpaextension.test.data.SomeFilter">
                <binding var="CID" attribute="creatorId"/>
                <binding var="NT" attribute="nameTxt"/>
            </filterClass>
        </query>
        <query id="MyOIQuery2" alias="oi" jpql="oi.creatorId=:CID and oi.nameTxt=:NT" annotation="anno6 anno7">
            <filterClass class="org.jpaextension.test.data.SomeJavaTestFilter">
                <binding var="CID" attribute="creatorId"/>
                <binding var="NT" attribute="nameTxt"/>
            </filterClass>
        </query>
        <query id="FindObjectItemFromName"
               jpql="select oi from ObjectItem oi where oi.nameTxt like ?1"/>

        <query id="FindObjectItemFromNameWithFilter" alias="oi" jpql="oi.nameTxt |MY_LIKE_SNIPPET| :N" orderby="oi.nameTxt">
            <filterClass class="org.jpaextension.test.NameFilter">
                <binding var="N" attribute="name"/>
            </filterClass>
        </query>
    </filter>

</jpaextension>

=== FaKod/JPA-for-Scala/ProofOfConcept/src/JPAExtension.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2010 FaKod resp. LinesOfCode. This is not free software
  -->

<jpaextension xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JPAExtension.xsd">

    <jpqlsnippets>
        <snippet id="nnaammee1" jpql="NAME=:UNITNAME"/>
        <snippet id="nnaammee2" jpql="NAME=:NAME"/>
        <snippet id="nnaammee3" jpql="NAME=:UNIT"/>
    </jpqlsnippets>


    <!-- Definition of available Query Objects-->
    <filter>
        <query id="UserFromName"
               jpql="select u from User u where u.name like ?1"/>

        <query id="FindUserFromName"
               jpql="select u from User u where u.name like ?1"/>

        <query id="DistancePointFromTextToLocID"
               jpql="select distance(pointfromtext(?1),lp.geometry) from location_point as lp where lp.loc_id=?2"/>

        <query id="AzimuthPointFromTextToLocID"
               jpql="select azimuth(pointfromtext(?1),lp.geometry) from location_point as lp where lp.loc_id=?2"/>

        <query id="CofFromUserId"
               jpql="select cof from CircleOfFriends cof where cof.ownerOfThisCircleOfFriends.id=?1"/>

        <query id="LocTagFromUserId"
               jpql="select lt from LocationTag lt where lt.userOwningThislocationTag.id=?1"/>

        <query id="LocTagFromCofId"
               jpql="select lt from LocationTag lt, User u, CircleOfFriends cof inner join cof.friends f where cof.id=?1 AND u.id=f.id AND lt.userOwningThislocationTag.id=u.id"/>
    </filter>

</jpaextension>
